server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallback-uri: forward:/userServiceFallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallback-uri: forward:/departmentServiceFallback
hystrix:
  commmand:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeOutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
